<#
.SYNOPSIS
  Start the isolated synthetic Windows desktop demo: PostgreSQL, Redis, API, worker, scheduler,
  dispatcher, explicit migrations, demo seed, readiness checks, then the Flutter Windows app.

.DESCRIPTION
  Uses an ignored .env.demo generated from .env.example (APP_ENV=local, DEMO_MODE=true, blank owner
  identity). The real .env is never read, created or modified. Compose runs under its own project
  name so demo containers and volumes are separate from ordinary local operation. The API binds only
  to 127.0.0.1:8000; PostgreSQL and Redis publish no host ports.

.PARAMETER BackendOnly
  Start and verify the backend but do not run the Flutter Windows app.

.PARAMETER SkipBuild
  Reuse the existing backend image instead of rebuilding it.

.PARAMETER SkipFlutterChecks
  Skip `flutter pub get --enforce-lockfile`, `flutter analyze` and `flutter test` before `flutter run`.

.PARAMETER ReadyTimeoutSeconds
  Maximum seconds to wait for /api/v1/health/ready to return 200.
#>
[CmdletBinding()]
param(
    [switch]$BackendOnly,
    [switch]$SkipBuild,
    [switch]$SkipFlutterChecks,
    [int]$ReadyTimeoutSeconds = 180
)

$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$ComposeFile = Join-Path $RepoRoot 'deployment\compose.local.yml'
$EnvExample = Join-Path $RepoRoot '.env.example'
$EnvDemo = Join-Path $RepoRoot '.env.demo'
$ProjectName = 'personal-staffer-demo'
$ApiBase = 'http://127.0.0.1:8000'

function Write-Step { param([string]$Message) Write-Host "==> $Message" -ForegroundColor Cyan }

function Invoke-Checked {
    # Run a native command; stop on a nonzero exit code with the exact command recorded.
    param([string]$File, [string[]]$Arguments)
    Write-Host "    $File $($Arguments -join ' ')" -ForegroundColor DarkGray
    & $File @Arguments
    if ($LASTEXITCODE -ne 0) { throw "Command failed (exit $LASTEXITCODE): $File $($Arguments -join ' ')" }
}

function Invoke-Compose {
    param([string[]]$Arguments)
    Invoke-Checked 'docker' (@('compose', '-p', $ProjectName, '-f', $ComposeFile) + $Arguments)
}

function Get-EnvValue {
    param([string[]]$Lines, [string]$Key)
    foreach ($line in $Lines) {
        if ($line -match "^\s*$([regex]::Escape($Key))\s*=\s*(.*)$") { return $Matches[1].Trim() }
    }
    return $null
}

function Invoke-Http {
    # Returns @{ Status; Body } without throwing on non-2xx so we can assert exact codes.
    param([string]$Url, [string]$Method = 'GET')
    try {
        $response = Invoke-WebRequest -Uri $Url -Method $Method -UseBasicParsing -TimeoutSec 5
        return @{ Status = [int]$response.StatusCode; Body = [string]$response.Content }
    } catch [System.Net.WebException] {
        $r = $_.Exception.Response
        if ($r) {
            $reader = New-Object System.IO.StreamReader($r.GetResponseStream())
            return @{ Status = [int]$r.StatusCode; Body = $reader.ReadToEnd() }
        }
        return @{ Status = 0; Body = $_.Exception.Message }
    } catch {
        return @{ Status = 0; Body = $_.Exception.Message }
    }
}

function Assert-Status {
    param([string]$Label, [hashtable]$Result, [int]$Expected)
    if ($Result.Status -eq $Expected) {
        Write-Host "    OK   $Label -> $($Result.Status)" -ForegroundColor Green
    } else {
        throw "$Label returned $($Result.Status), expected $Expected. Body: $($Result.Body)"
    }
}

# --- 1. Safety: docker engine and the demo env file --------------------------------------
Write-Step 'Checking Docker engine'
& docker version --format '{{.Server.Version}}' *> $null
if ($LASTEXITCODE -ne 0) { throw 'Docker engine is not reachable. Start Docker Desktop, then rerun.' }

Write-Step 'Preparing ignored .env.demo (the real .env is never touched)'
if (-not (Test-Path $EnvExample)) { throw ".env.example missing at $EnvExample" }
if (-not (Test-Path $EnvDemo)) {
    $lines = Get-Content $EnvExample
    $overrides = @{
        'APP_ENV' = 'local'
        'PUBLIC_BASE_URL' = $ApiBase
        'DEMO_MODE' = 'true'
        'OWNER_ALLOWED_EMAIL' = ''
        'OWNER_GOOGLE_SUBJECT' = ''
        'GOOGLE_CLIENT_ID' = ''
        'GOOGLE_CLIENT_SECRET' = ''
        'GOOGLE_REDIRECT_URI' = ''
        'GMAIL_REDIRECT_URI' = ''
        'TOKEN_ENCRYPTION_KEY' = ''
        'JOBSPY_ENABLED' = 'false'
    }
    $output = New-Object System.Collections.Generic.List[string]
    $output.Add('# Generated by scripts/start_desktop_demo.ps1 for the synthetic Windows desktop demo.')
    $output.Add('# Ignored by Git. Never copy these values into .env or a nonlocal deployment.')
    foreach ($line in $lines) {
        $written = $false
        foreach ($key in $overrides.Keys) {
            if ($line -match "^\s*$([regex]::Escape($key))\s*=") {
                $output.Add("$key=$($overrides[$key])")
                $written = $true
                break
            }
        }
        if (-not $written) { $output.Add($line) }
    }
    # Write without a BOM so the container's dotenv parser sees a clean first key.
    [System.IO.File]::WriteAllLines($EnvDemo, $output, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "    Created $EnvDemo"
} else {
    Write-Host "    Reusing existing $EnvDemo"
}
$demoLines = Get-Content $EnvDemo
if ((Get-EnvValue $demoLines 'APP_ENV') -ne 'local') { throw '.env.demo must set APP_ENV=local' }
if ((Get-EnvValue $demoLines 'DEMO_MODE') -ne 'true') { throw '.env.demo must set DEMO_MODE=true' }
foreach ($secretKey in 'GOOGLE_CLIENT_SECRET', 'TOKEN_ENCRYPTION_KEY', 'PEOPLE_SEARCH_API_KEY', 'USAJOBS_API_KEY') {
    if (Get-EnvValue $demoLines $secretKey) { throw ".env.demo must not carry a real $secretKey; the demo is credential-free." }
}
& git -C $RepoRoot check-ignore -q .env.demo
if ($LASTEXITCODE -ne 0) { throw '.env.demo is not Git-ignored; refusing to continue.' }
$env:STAFFER_ENV_FILE = $EnvDemo

# --- 2. Backend containers ------------------------------------------------------------------
Push-Location $RepoRoot
try {
    if (-not $SkipBuild) {
        Write-Step 'Building backend development image'
        Invoke-Compose @('build', 'api')
    }

    Write-Step 'Starting PostgreSQL and Redis (no host ports published)'
    Invoke-Compose @('up', '-d', '--wait', 'postgres', 'redis')

    Write-Step 'Applying Alembic migrations explicitly (once, before any worker starts)'
    Invoke-Compose @('run', '--rm', '--no-deps', 'api', 'alembic', 'upgrade', 'head')

    Write-Step 'Starting API, worker, scheduler and dispatcher'
    Invoke-Compose @('up', '-d', 'api', 'worker', 'scheduler', 'dispatcher')

    Write-Step 'Waiting for /api/v1/health/live'
    $deadline = (Get-Date).AddSeconds($ReadyTimeoutSeconds)
    do {
        $live = Invoke-Http "$ApiBase/api/v1/health/live"
        if ($live.Status -eq 200) { break }
        Start-Sleep -Seconds 2
    } while ((Get-Date) -lt $deadline)
    Assert-Status 'GET /api/v1/health/live' $live 200

    Write-Step 'Seeding the clearly synthetic demo dataset'
    Invoke-Compose @('run', '--rm', '--no-deps', 'api', 'python', '-m', 'app.cli', 'demo-seed')

    Write-Step 'Waiting for /api/v1/health/ready'
    do {
        $ready = Invoke-Http "$ApiBase/api/v1/health/ready"
        if ($ready.Status -eq 200) { break }
        Start-Sleep -Seconds 3
    } while ((Get-Date) -lt $deadline)
    Assert-Status 'GET /api/v1/health/ready' $ready 200

    Write-Step 'Verifying demo state and unauthenticated rejection'
    $version = Invoke-Http "$ApiBase/api/v1/version"
    Assert-Status 'GET /api/v1/version' $version 200
    $versionJson = $version.Body | ConvertFrom-Json
    if ($versionJson.demo_mode -ne $true) { throw "Backend reports demo_mode=$($versionJson.demo_mode); expected true." }
    Write-Host "    OK   backend $($versionJson.backend_version) demo_mode=true" -ForegroundColor Green
    Assert-Status 'GET /api/v1/jobs (no session)' (Invoke-Http "$ApiBase/api/v1/jobs") 401
    Assert-Status 'GET /api/v1/notifications (no session)' (Invoke-Http "$ApiBase/api/v1/notifications") 401
    Assert-Status 'GET /openapi.json (root, must not exist)' (Invoke-Http "$ApiBase/openapi.json") 404
    Assert-Status 'GET /docs (root, must not exist)' (Invoke-Http "$ApiBase/docs") 404

    Write-Host ''
    Write-Host "Demo backend is ready at $ApiBase (compose project '$ProjectName', env file .env.demo)." -ForegroundColor Green
    Write-Host "Stop it with scripts\stop_desktop_demo.ps1 (the demo database volume is preserved)."
} finally {
    Pop-Location
}

if ($BackendOnly) { exit 0 }

# --- 3. Flutter Windows client --------------------------------------------------------------
Write-Step 'Launching the Flutter Windows app against the demo backend'
$flutter = $null
try { $flutter = (Get-Command flutter -ErrorAction Stop).Source } catch { }
if (-not $flutter) { throw 'flutter is not on PATH. Run scripts\check_desktop_prerequisites.ps1 for the exact requirement.' }
$env:CI = 'true'
Push-Location (Join-Path $RepoRoot 'client')
try {
    if (-not $SkipFlutterChecks) {
        Invoke-Checked $flutter @('--suppress-analytics', 'pub', 'get', '--enforce-lockfile')
        Invoke-Checked $flutter @('--suppress-analytics', 'analyze')
        Invoke-Checked $flutter @('--suppress-analytics', 'test')
    }
    Invoke-Checked $flutter @('--suppress-analytics', 'run', '-d', 'windows', "--dart-define=API_BASE_URL=$ApiBase", '--dart-define=DEMO_MODE=true')
} finally {
    Pop-Location
}
